# Generated by Django 4.1.7 on 2023-12-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=50)),
                ("item_photo", models.ImageField(upload_to=None)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("count", models.IntegerField()),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itemdings",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("identity", models.UUIDField()),
                ("username", models.CharField(max_length=50)),
                ("gifted", models.BooleanField(default=False)),
                ("giver", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "staff",
                "verbose_name_plural": "staff",
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("recipient", models.CharField(max_length=255)),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding_app.staff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding_app.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
    ]
