# Generated by Django 4.1.7 on 2023-12-11 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bidding_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AlterField(
            model_name="staff",
            name="identity",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
