# Generated by Django 4.1.7 on 2023-12-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bidding_app", "0002_alter_item_options_alter_staff_identity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"verbose_name": "Bid", "verbose_name_plural": "Bids"},
        ),
    ]
