# Generated by Django 4.1.7 on 2023-12-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bidding_app", "0003_alter_bid_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bidding_app.item",
                verbose_name="Item",
            ),
        ),
    ]
