# Generated by Django 4.1.7 on 2023-12-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bidding_app", "0004_alter_bid_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="giver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="bidding_app.staff",
                verbose_name="Staff",
            ),
        ),
    ]
