# Generated by Django 4.1.7 on 2023-12-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding_app", "0005_alter_bid_giver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="recipient",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
