# Generated by Django 4.1.7 on 2023-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding_app", "0007_alter_bid_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
